### ISSUE TITLE
Failed to clone the repo.

### ISSUE THREAD

**Issue by yyoshiaki** [rikenbit/RamDAQ-prototype#1]
https://github.com/rikenbit/RamDAQ#3-clone-this-repository

```
cd
git clone rikenbit/RamDAQ
```

->

```
cd
git clone https://github.com/rikenbit/RamDAQ.git
```

This may be the right?

**Comment by yuifu** [comment]
Thank you for the question. You're right. It's our mistake.

I've fixed the command in README.md https://github.com/rikenbit/RamDAQ/commit/5a83d05d6f85d0226f7ea2a5683bbadd7f33934d
